window.onload = function(){
    let app = new Vue({
        el:"#app",
        data:{
            itemList:[
                {
                    title:"安全可搜索云存储",
                    introduction:"多关键词相关性排序可搜索云存储app：前端使用@vue/cli搭建脚手架并通过hbuilder打包为安卓app，服务器通过linux + apache + mysql + django的模式实现后端api，前后端分离。1.数据所有者建立密文系统，分享共享信息使得其他人可以搜索文件。2.支持加密状态下多个关键词按照相关性顺序返回结果。3.数据所有者可对每个用户和文件进行属性访问权限控制。",
                    imageList:[
                        "project/searchable_encryption/1.jpg",
                        "project/searchable_encryption/2.jpg",
                        "project/searchable_encryption/3.jpg",
                        "project/searchable_encryption/4.jpg",
                        "project/searchable_encryption/5.jpg",
                        "project/searchable_encryption/6.jpg",
                        "project/searchable_encryption/7.jpg",
                        "project/searchable_encryption/8.jpg",
                        "project/searchable_encryption/9.jpg",
                        "project/searchable_encryption/10.jpg",
                        "project/searchable_encryption/11.jpg",
                        "project/searchable_encryption/12.jpg",
                        "project/searchable_encryption/13.jpg",
                        "project/searchable_encryption/14.jpg",
                        "project/searchable_encryption/15.jpg",
                        "project/searchable_encryption/16.jpg",
                        "project/searchable_encryption/17.jpg"
                    ],
                    rawImage:true,
                    width:200,
                    entrance:"https://github.com//BINGOGO123/Encrypted-cloud-storage-app/releases/download/v1.0.0/searchable.encryption.apk",
                    codeAddress:"https://github.com/BINGOGO123/Encrypted-cloud-storage-app",
                    entranceInfo:"下载",
                    entranceLogo:"fa-arrow-circle-down"
                },
                {
                    title:"同济大学小社区",
                    introduction:"一个社区交流平台，用户以及发布文章活动以及评论参与等，有完整的个人动态；管理员具有管理用户、文章、活动评论以及发布公告等功能；移动端适配",
                    imageList:[
                        "project/tongjicircle/1.PNG",
                        "project/tongjicircle/2.PNG",
                        "project/tongjicircle/3.PNG",
                        "project/tongjicircle/4.PNG",
                        "project/tongjicircle/5.PNG",
                        "project/tongjicircle/6.PNG",
                        "project/tongjicircle/7.PNG",
                        "project/tongjicircle/8.PNG",
                        "project/tongjicircle/9.PNG",
                        "project/tongjicircle/10.PNG",
                        "project/tongjicircle/11.PNG",
                        "project/tongjicircle/12.PNG"
                    ],
                    entrance:"https://bingoz.cn/tongjicircle",
                    codeAddress:"https://github.com/BINGOGO123/tongjicircle",
                    entranceInfo:"前往",
                    entranceLogo:"fa-arrow-circle-right"
                },
                {
                    title:"云文件夹",
                    introduction:"基于vue.js搭建的云文件夹系统，用户可以在线管理自己的文件夹和编辑文件等",
                    imageList:[
                        "project/editor/1.PNG",
                        "project/editor/2.PNG",
                        "project/editor/3.PNG",
                        "project/editor/4.PNG"
                    ],
                    entrance:"https://www.bingoz.cn/editor",
                    codeAddress:"https://github.com/BINGOGO123/cloud_editor",
                    entranceInfo:"前往",
                    entranceLogo:"fa-arrow-circle-right"
                },
                {
                    title:"windows平台简易C编译器",
                    introduction:"c++编写的c编译器，用户界面采用electron实现",
                    imageList:[
                        "project/compiler/1.PNG",
                        "project/compiler/2.PNG",
                        "project/compiler/3.PNG"
                    ],
                    entrance:"https://www.bingoz.cn/download/compiler_win64.zip",
                    codeAddress:false,
                    entranceInfo:"下载",
                    entranceLogo:"fa-arrow-circle-down"
                },
                {
                    title:"学习能力评测",
                    introduction:"面向计算机专业学生的基于层次分析法的学习能力评测（玄学）",
                    imageList:[
                        "project/sitp/1.PNG",
                        "project/sitp/2.PNG"
                    ],
                    entrance:"https://www.bingoz.cn/sitp",
                    codeAddress:"https://github.com/BINGOGO123/study-test",
                    entranceInfo:"前往",
                    entranceLogo:"fa-arrow-circle-right"
                },
                {
                    title:"web聊天室",
                    introduction:"基于http轮询的聊天室，另有答题功能；图片未压缩，所以网页加载速度很慢",
                    imageList:[
                        "project/web_chat/1.PNG",
                        "project/web_chat/2.PNG",
                        "project/web_chat/3.PNG"
                    ],
                    entrance:"https://www.bingoz.cn/web-exp-5",
                    codeAddress:"https://www.bingoz.cn/download/web-chat.zip",
                    entranceInfo:"前往",
                    entranceLogo:"fa-arrow-circle-right"
                },
                {
                    title:"windows聊天软件",
                    introduction:"windows聊天软件，其中网络交互部分均使用tcp socket自定义报文实现，支持文件传输；桌面应用使用qt编写，服务器使用标准c++编写；未启动服务端守护进程故目前无法登录使用",
                    imageList:[
                        "project/chat/1.PNG"
                    ],
                    entrance:"https://www.bingoz.cn/download/chat.zip",
                    codeAddress:false,
                    entranceInfo:"下载",
                    entranceLogo:"fa-arrow-circle-down"
                },
                {
                    title:"顺丰快递信息批量下载",
                    introduction:"一键下载所有最新运单号、时间、托寄物信息；自动登录，但是目前尚未解决验证码识别，因此需要人工输入验证码",
                    imageList:[],
                    entrance:false,
                    codeAddress:"https://github.com/BINGOGO123/shunfeng-downloader",
                    entranceInfo:"下载",
                    entranceLogo:"fa-arrow-circle-down"
                },
                {
                    title:"QR CODE协议实现",
                    introduction:"使用C++从头到尾实现的QR CODE协议生成部分，可以自定义版本号和纠错等级；下图为40版本H纠错二维码，需要耐心扫描",
                    imageList:[
                        "project/qr_code/1.PNG"
                    ],
                    rawImage:true,
                    entrance:false,
                    codeAddress:"https://github.com/BINGOGO123/qr-code",
                    entranceInfo:"下载",
                    entranceLogo:"fa-arrow-circle-down"
                }
            ]
        }
    });
}